//! Bakes `assets/svg/*.svg` into static GPU mesh data (vertex/index arrays)
//! at build time — see `assets/svg/README.md` for the authoring convention
//! this depends on. Runs on the host regardless of the crate's own target
//! (`[build-dependencies]` always build for the host), so `usvg`/`lyon`
//! never end up in the shipped wasm binary — only their plain `f32`/`u16`
//! output does, via `include!` from `src/render/meshes.rs`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use lyon::math::point;
use lyon::path::Path as LyonPath;
use lyon::tessellation::{
    BuffersBuilder, FillOptions, FillTessellator, FillVertex, FillVertexConstructor,
    VertexBuffers,
};

/// Mirrors `render::meshes::Vertex` — kept as a separate build-time-only
/// type (this file is a different crate compilation entirely) rather than
/// shared, since the generated output only needs to match `Vertex`'s field
/// names/shape textually, not its actual Rust type.
#[derive(Copy, Clone, Debug, PartialEq)]
struct BakedVertex {
    position: [f32; 2],
    color: [f32; 3],
}

/// Paint that usvg couldn't resolve to a flat color (gradient/pattern, not
/// yet supported by this pipeline — see assets/svg/README.md rule 5).
/// Deliberately loud so a missed case is obvious in the running app, not a
/// silent wrong color.
const UNSUPPORTED_PAINT_COLOR: [f32; 3] = [1.0, 0.0, 1.0];

struct VertexCtor {
    color: [f32; 3],
}

impl FillVertexConstructor<BakedVertex> for VertexCtor {
    fn new_vertex(&mut self, vertex: FillVertex) -> BakedVertex {
        let p = vertex.position();
        BakedVertex {
            position: [p.x, p.y],
            color: self.color,
        }
    }
}

fn main() {
    let assets_dir = Path::new("assets/svg");
    println!("cargo:rerun-if-changed={}", assets_dir.display());

    let mut svg_paths: Vec<PathBuf> = fs::read_dir(assets_dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", assets_dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|ext| ext == "svg"))
        .collect();
    // Deterministic order so the generated file doesn't churn from
    // directory-listing order alone.
    svg_paths.sort();

    let mut generated = String::from(
        "// @generated by build.rs from assets/svg/*.svg — do not edit by hand.\n\
         pub static GENERATED_MESHES: &[(&str, &[Vertex], &[u16])] = &[\n",
    );

    for svg_path in &svg_paths {
        let name = svg_path
            .file_stem()
            .unwrap()
            .to_string_lossy()
            .into_owned();
        let (vertices, indices) = tessellate_svg(svg_path);
        write_mesh_entry(&mut generated, &name, &vertices, &indices);
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("meshes_generated.rs");
    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}

fn write_mesh_entry(out: &mut String, name: &str, vertices: &[BakedVertex], indices: &[u16]) {
    out.push_str(&format!("    (\"{name}\", &[\n"));
    for v in vertices {
        out.push_str(&format!(
            "        Vertex {{ position: [{:?}, {:?}], color: [{:?}, {:?}, {:?}] }},\n",
            v.position[0], v.position[1], v.color[0], v.color[1], v.color[2],
        ));
    }
    out.push_str("    ], &[\n        ");
    for (i, index) in indices.iter().enumerate() {
        out.push_str(&format!("{index}, "));
        if i % 24 == 23 {
            out.push_str("\n        ");
        }
    }
    out.push_str("\n    ]),\n");
}

/// Parses and tessellates one SVG file into a combined mesh — every
/// `<path>`/`<rect>`/`<circle>`/etc. in the file (usvg resolves basic shapes
/// to paths) becomes triangles in the same vertex/index buffer, each
/// carrying its own path's flat fill color.
fn tessellate_svg(svg_path: &Path) -> (Vec<BakedVertex>, Vec<u16>) {
    let svg_text = fs::read_to_string(svg_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", svg_path.display()));
    let tree = usvg::Tree::from_str(&svg_text, &usvg::Options::default())
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", svg_path.display()));

    let mut geometry: VertexBuffers<BakedVertex, u16> = VertexBuffers::new();
    let mut tessellator = FillTessellator::new();

    let mut paths = Vec::new();
    collect_paths(tree.root(), &mut paths);

    // usvg bakes the SVG's viewBox-to-viewport transform into every path's
    // `abs_transform` — so path coordinate (0, 0) does *not* land at local
    // (0, 0) after transforming, it lands wherever the viewBox's declared
    // min-x/min-y happens to map to. Re-centering by this file's own anchor
    // offset (computed once, from whichever path happens to be first —
    // correct as long as sibling shapes share one transform, i.e. this
    // asset has no nested per-shape `transform=` attributes) makes "path
    // coordinate (0, 0) is the anchor" true regardless of viewBox, so
    // authors never need to think about viewBox bounds at all.
    let anchor_offset = paths
        .first()
        .map(|p| transform_and_flip(p.abs_transform(), usvg::tiny_skia_path::Point::zero()))
        .unwrap_or_else(|| point(0.0, 0.0));

    for usvg_path in paths {
        let color = fill_color(usvg_path);
        let lyon_path = build_lyon_path(usvg_path, anchor_offset);
        tessellator
            .tessellate_path(
                &lyon_path,
                &FillOptions::default(),
                &mut BuffersBuilder::new(&mut geometry, VertexCtor { color }),
            )
            .unwrap_or_else(|e| {
                panic!("tessellation failed for {}: {e:?}", svg_path.display())
            });
    }

    (geometry.vertices, geometry.indices)
}

fn collect_paths<'a>(group: &'a usvg::Group, out: &mut Vec<&'a usvg::Path>) {
    for node in group.children() {
        match node {
            usvg::Node::Group(g) => collect_paths(g, out),
            usvg::Node::Path(p) if p.is_visible() => out.push(p),
            _ => {}
        }
    }
}

fn fill_color(path: &usvg::Path) -> [f32; 3] {
    match path.fill().map(|f| f.paint()) {
        Some(usvg::Paint::Color(c)) => [
            c.red as f32 / 255.0,
            c.green as f32 / 255.0,
            c.blue as f32 / 255.0,
        ],
        _ => UNSUPPORTED_PAINT_COLOR,
    }
}

/// Applies `transform` then flips Y (SVG is y-down, our render space is
/// y-up — see assets/svg/README.md rule 3).
fn transform_and_flip(
    transform: usvg::tiny_skia_path::Transform,
    mut p: usvg::tiny_skia_path::Point,
) -> lyon::math::Point {
    transform.map_point(&mut p);
    point(p.x, -p.y)
}

/// Converts one usvg path (already flattened to Move/Line/Quad/Cubic/Close
/// by usvg, in its own pre-transform local space) into a lyon path in the
/// asset's final local mesh space, re-centered by `anchor_offset` (see
/// `tessellate_svg`) so path coordinate (0, 0) is always the mesh's anchor.
/// No scaling beyond that: 1 baked unit is 1 raw SVG user unit (rule 4).
fn build_lyon_path(path: &usvg::Path, anchor_offset: lyon::math::Point) -> LyonPath {
    let transform = path.abs_transform();
    let to_local = |p: usvg::tiny_skia_path::Point| -> lyon::math::Point {
        let p = transform_and_flip(transform, p);
        point(p.x - anchor_offset.x, p.y - anchor_offset.y)
    };

    let mut builder = LyonPath::builder();
    let mut in_subpath = false;
    for segment in path.data().segments() {
        match segment {
            usvg::tiny_skia_path::PathSegment::MoveTo(p) => {
                if in_subpath {
                    builder.end(false);
                }
                builder.begin(to_local(p));
                in_subpath = true;
            }
            usvg::tiny_skia_path::PathSegment::LineTo(p) => {
                builder.line_to(to_local(p));
            }
            usvg::tiny_skia_path::PathSegment::QuadTo(ctrl, p) => {
                builder.quadratic_bezier_to(to_local(ctrl), to_local(p));
            }
            usvg::tiny_skia_path::PathSegment::CubicTo(c1, c2, p) => {
                builder.cubic_bezier_to(to_local(c1), to_local(c2), to_local(p));
            }
            usvg::tiny_skia_path::PathSegment::Close => {
                builder.end(true);
                in_subpath = false;
            }
        }
    }
    if in_subpath {
        builder.end(false);
    }
    builder.build()
}
